name: Free Kubernetes CI/CD with KIND

on:
  push:
    branches: [ "main" ]

jobs:
  k8s-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t hello-k8s:latest .

      - name: Create Kubernetes cluster (KIND)
        uses: helm/kind-action@v1.8.0
        with:
            cluster_name: kind
            wait: 120s


      - name: Load Docker image into KIND
        run: kind load docker-image hello-k8s:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for deployment to be ready
        run: kubectl rollout status deployment/hello-deployment

      - name: Show application logs
        run: kubectl logs deployment/hello-deployment
